name: Foundry Check Suite

on:
  push:
    paths: ['**.sol', '**.toml']
    branches: [master, develop]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  FORCE_COLOR: 2
  FOUNDRY_PROFILE: ci
  COVERAGE_SENSITIVITY_PERCENT: 1

jobs:
  # Initial check creation job
  create-check-suite:
    runs-on: ubuntu-latest
    outputs:
      check_suite_id: ${{ steps.create_suite.outputs.check_suite_id }}
    steps:
      - id: create_suite
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const suite = await github.rest.checks.createSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha
            });
            return suite.data.id;

  matrix-test:
    needs: create-check-suite
    name: Foundry ${{ matrix.foundry-version }} / Solc ${{ matrix.solc-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - foundry-version: 'nightly'
            solc-version: '0.8.26'
            check-name: 'Foundry Nightly - Solc 0.8.26'
          - foundry-version: 'nightly'
            solc-version: '0.8.27'
            check-name: 'Foundry Nightly - Solc 0.8.27'
          - foundry-version: 'stable'
            solc-version: '0.8.26'
            check-name: 'Foundry Stable - Solc 0.8.26'
            primary: true
          - foundry-version: 'stable'
            solc-version: '0.8.27'
            check-name: 'Foundry Stable - Solc 0.8.27'
    
    steps:
      # Create check run for this matrix combination
      - name: Create Check Run
        id: create_check
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const check = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: '${{ matrix.check-name }}',
              head_sha: context.sha,
              status: 'in_progress',
              output: {
                title: 'Test Run Started',
                summary: 'Running Foundry tests...',
                text: 'Initializing test environment'
              }
            });
            console.log(`Created check run ID: ${check.data.id}`);
            return check.data.id;
      
      - uses: actions/checkout@v4
      
      - name: Update Check - Setup
        uses: actions/github-script@v7.0.1
        with:
          script: |
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: '${{ steps.create_check.outputs.result }}',
              status: 'in_progress',
              output: {
                title: 'Setting up environment',
                summary: 'Installing dependencies and configuring environment',
                text: 'Installing Foundry and dependencies...'
              }
            });
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ matrix.foundry-version }}
      
      - name: Configure Solc
        run: forge config solc ${{ matrix.solc-version }}
      
      - name: Install Dependencies
        run: forge install
      
      - name: Update Check - Building
        uses: actions/github-script@v7.0.1
        with:
          script: |
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: '${{ steps.create_check.outputs.result }}',
              status: 'in_progress',
              output: {
                title: 'Building Contracts',
                summary: 'Compiling smart contracts...',
                text: 'Running forge build...'
              }
            });
      
      - name: Build
        id: build
        run: |
          forge build --sizes > build_output.txt
          echo "build_output<<EOF" >> $GITHUB_OUTPUT
          cat build_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Update Check - Testing
        uses: actions/github-script@v7.0.1
        with:
          script: |
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: '${{ steps.create_check.outputs.result }}',
              status: 'in_progress',
              output: {
                title: 'Running Tests',
                summary: 'Executing test suite...',
                text: 'Running forge test...'
              }
            });
      
      - name: Test
        id: test
        run: |
          forge test -vv > test_output.txt
          echo "test_output<<EOF" >> $GITHUB_OUTPUT
          cat test_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run coverage
        shell: bash
        id: forge_coverage
        run: forge coverage --report summary --report lcov

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Filter directories
        run: lcov --remove lcov.info 'test/*' 'script/*' --output-file lcovNew.info --rc lcov_branch_coverage=1 --rc derive_function_end_line=0 --ignore-errors unused

      - name: Capture coverage output
        id: new-coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcovNew.info

      - name: Retrieve previous coverage
        uses: actions/download-artifact@v4.2.1
        id: ci_previous_coverage
        with:
          name: coverage
          path: coverage.info
        continue-on-error: true

      - name: Check if a previous coverage exists
        id: ci_coverage
        run: |
          if [ ! -f coverage.info ] && [ ! -d coverage.info ]; then
            echo "Artifact not found. Initializing at 0"
            echo "0" > coverage.info
          fi

      - name: Compare previous coverage
        run: |
          old=$(cat coverage.info)
          new=$(( ${{ steps.new-coverage.outputs.total-coverage }} + ${{ env.COVERAGE_SENSITIVITY_PERCENT }} ))
          if [ "$new" -lt "$old" ]; then
            echo "Coverage decreased from $old to $new"
            exit 1
          fi
          mv lcovNew.info coverage.info

      - name: Upload the new coverage
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage
          path: coverage.info

      - name: Update Check - Complete
        if: always()
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const buildSuccess = '${{ steps.build.outcome }}' === 'success';
            const testSuccess = '${{ steps.test.outcome }}' === 'success';
            const success = buildSuccess && testSuccess;
            
            const buildOutput = `${{ steps.build.outputs.build_output }}`;
            const testOutput = `${{ steps.test.outputs.test_output }}`;
            
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: '${{ steps.create_check.outputs.result }}',
              status: 'completed',
              conclusion: success ? 'success' : 'failure',
              output: {
                title: success ? 'All Tests Passed' : 'Tests Failed',
                summary: `Build: ${buildSuccess ? '✅' : '❌'}\nTests: ${testSuccess ? '✅' : '❌'}`,
                text: '```\n' + 
                      'Build Output:\n' + 
                      buildOutput + 
                      '\n\nTest Output:\n' + 
                      testOutput +
                      '\n```'
              }
            });

  # Final status update
  update-check-suite:
    needs: [create-check-suite, matrix-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Check Suite Status
        uses: actions/github-script@v6
        with:
          script: |
            const success = '${{ needs.matrix-test.result }}' === 'success';
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_suite_id: '${{ needs.create-check-suite.outputs.check_suite_id }}',
              status: 'completed',
              conclusion: success ? 'success' : 'failure'
            });
